name: Build .deb

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npm install caxa
      - run: npm install .
      - run: npx caxa --input . --output ghost-inspector  -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/bin/ghost-inspector"
      - run: VERSION=$(npm list ghost-inspector --depth 0 | grep ghost | cut -d '@' -f2 | cut -d ' ' -f1)
      - run: echo $VERSION
      - run: sudo apt-get -y install dh-make devscripts
      - run: |
        mkdir ghost-inspector-$VERSION && cd ghost-inspector-$VERSION
        cp ../ghost-inspector .
        export DEBEMAIL="support@ghostinspector.com"
        export DEBFULLNAME="Ghost Inpsector"
        dh_make --indep --createorig
        touch debian/install
        echo "ghost-inspector usr/bin" > debian/install
        debuild -us -uc
      - run: ls -l
