name: Build .deb

on: [push]

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # tag_name: ${{ github.ref }}
          tag_name: v6.0.6-alpha
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
  build:
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary: -linux
          - os: macos-latest
            binary: -macos
          - os: windows-latest
            binary: .exe
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g caxa node-prune
      - run: npm install . --production
      - run: node-prune
      - run: npx caxa --input . --output ghost-inspector${{ matrix.binary }}  -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/bin/ghost-inspector"
      - run: ls -l
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: ghost-inspector${{ matrix.binary }}
          asset_path: ./ghost-inspector${{ matrix.binary }}
          asset_content_type: application/octet-stream

