name: Build and release binaries

on:
  push:
    tags:
      - 'v[0-9]+.*'

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  build:
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary: -linux
          # macos build not working properly, disabling for now
          # - os: macos-latest
          #   binary: -macos
          - os: windows-latest
            binary: .exe
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g caxa node-prune
      - run: npm install . --production
      - run: node-prune
      - run: npx caxa --input . --output ghost-inspector${{ matrix.binary }}  -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/bin/ghost-inspector"
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: ghost-inspector${{ matrix.binary }}
          asset_path: ./ghost-inspector${{ matrix.binary }}
          asset_content_type: application/octet-stream
      - name: Archive binary
        uses: actions/upload-artifact@v2
        with:
          name: binary-${{ matrix.os }}
          path: ./ghost-inspector${{ matrix.binary }}